"""add audio status

Revision ID: 1e28b43833b6
Revises: bf63f47e8199
Create Date: 2026-09-17 18:08:45.372578

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "1e28b43833b6"
down_revision: Union[str, Sequence[str], None] = "bf63f47e8199"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # PostgreSQL requires the enum type to exist before adding a column using it.
    audiostatus = sa.Enum(
        "pending", "processing", "completed", "failed", name="audiostatus"
    )
    audiostatus.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audio",
        sa.Column(
            "status",
            audiostatus,
            nullable=False,
            server_default="pending",
        ),
    )
    op.alter_column(
        "audio", "censored_file_path", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audio", "censored_file_path", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("audio", "status")
    audio_status_enum = sa.Enum(
        "pending",
        "processing",
        "completed",
        "failed",
        name="audiostatus",
    )
    sa.Enum(name="audiostatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
