"""add credits

Revision ID: 54a43d2b4eb3
Revises: 8f11e2e305b3
Create Date: 2026-09-22 12:42:56.876222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '54a43d2b4eb3'
down_revision: Union[str, Sequence[str], None] = '8f11e2e305b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio', sa.Column('duration', sa.Integer(), nullable=False))
    op.add_column('audio', sa.Column('credits_used', sa.Integer(), nullable=False))
    op.add_column('audio', sa.Column('credits_reserved', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('credits', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'credits')
    op.drop_column('audio', 'credits_reserved')
    op.drop_column('audio', 'credits_used')
    op.drop_column('audio', 'duration')
    # ### end Alembic commands ###