"""update audio

Revision ID: 8f11e2e305b3
Revises: 1e28b43833b6
Create Date: 2026-09-18 13:26:09.945623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f11e2e305b3'
down_revision: Union[str, Sequence[str], None] = '1e28b43833b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sound_effect',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('audio', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('audio', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('audio', sa.Column('transcription', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audio', sa.Column('use_beep', sa.Boolean(), nullable=False))
    op.add_column('audio', sa.Column('user_list', postgresql.ARRAY(sa.TEXT()), nullable=True))
    op.add_column('audio', sa.Column('sound_effect_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'audio', 'sound_effect', ['sound_effect_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audio', type_='foreignkey')
    op.drop_column('audio', 'sound_effect_id')
    op.drop_column('audio', 'user_list')
    op.drop_column('audio', 'use_beep')
    op.drop_column('audio', 'transcription')
    op.drop_column('audio', 'name')
    op.drop_column('audio', 'updated_at')
    op.drop_table('sound_effect')
    # ### end Alembic commands ###