"""propel auth

Revision ID: bd66d6c33e4b
Revises: 54a43d2b4eb3
Create Date: 2026-09-23 10:51:46.555950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bd66d6c33e4b'
down_revision: Union[str, Sequence[str], None] = '54a43d2b4eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('propelauth_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_user_propelauth_id'), 'user', ['propelauth_id'], unique=True)
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_propelauth_id'), table_name='user')
    op.drop_column('user', 'propelauth_id')
    # ### end Alembic commands ###